### ISSUE TITLE
TypeError: null is not an object (evaluating 'this.content.style')

### ISSUE THREAD

**Issue by aribronstein** [SparebankenVest/react-css-collapse#13]
I'm not sure what is causing this issue specifically only that it happens sporadically.

stacktrace:

webpack:///~/react-css-collapse/lib/components/Collapse.js:99setContentStyleProperty	
  
```
  }, {
    key: 'setContentStyleProperty',
    value: function setContentStyleProperty(property, value) {
      this.content.style[property] = value;
    }
  }, {
    key: 'setCollapsed',

```
webpack:///~/react-css-collapse/lib/components/Collapse.js:104setCollapsed	
 ```
 }, {
    key: 'setCollapsed',
    value: function setCollapsed() {
      this.setContentStyleProperty('height', '0px');
      this.setContentStyleProperty('overflow', 'hidden');
    }
  }, {

```

**Comment by thalseth** [comment]
Hi @aribronstein !
What version of the package are you using? 
Does this error typically occur on initial render? 
It would be very nice to provide an example for me to fully understand the issue. You can use the existing storybook project to provide a new story replicating your setup.
