### ISSUE TITLE
Possibility to specify CSS transition as component property

### ISSUE THREAD

**Issue by grubersjoe** [SparebankenVest/react-css-collapse#20]
Thank you for this component. It work's quite well :).

However, I have an idea for improvement: Right now it is required to specify the `className` to set the desired CSS transition. While this might be fine for most use cases, because most people should have some kind of CSS-in-JS solution or a bundler in use anyway, it is also somewhat limiting. In my opinion it would be very handy, if the transition could also be set directly as Component property. This way users are not forced to use some library to inject the styles into the HTML or to do this manually.

Example:

```js
<Collapse isOpen={isOpen} transition="height 250ms cubic-bezier(.4, 0, .2, 1)">
   <div>foo</div>
</Collapse>
```

Moreover it might be a good idea to offer a reasonable default transition (could be the default value of this potentially new component property). I was confused first, because the element collapsed without an animation. I think you should make it clearer in the README, that it is required to define a CSS transition first to make the animation work.

**Comment by thalseth** [comment]
Nice that you like it @grubersjoe! In version `3.4.0` the className is set by default but you still have to define the style in your own stylesheet.

Thank you for the feedback. I added a section to the readme to prevent confusion in the future 😊 

For now i think it is best to specify the transition yourself but i like the idea of a self contained component including style. If we specify the style the way you propose we have to provide all prefixes. Maybe that is not a big problem. But what if you dont actually want a transition. Then we have to specify transition="" ? Maybe you can create a PR with this feature @grubersjoe ? 🌈

**Comment by deshiknaves** [comment]
I've added this in the PR above. By default its not set, if it's defined, it will be added to the styles.

**Comment by thalseth** [comment]
Thanks again @deshiknaves! Great work.

**Comment by grubersjoe** [comment]
@deshiknaves was :smile:. Thank you for adding the feature!

About prefixing of the CSS transition rule: it's supported since IE10, so I guess this should be fine without the prefixes.

**Comment by grubersjoe** [comment]
@deshiknaves was faster :smile:. Thank you for adding the feature! It works as expected.

About prefixing the CSS transition: it's supported since IE10, so I guess this should be fine without IE specific prefixes.
