### ISSUE TITLE
ComponentWillReceiveProps warning after upgrade to React 16.9.0

### ISSUE THREAD

**Issue by petrloukota** [SparebankenVest/react-css-collapse#25]
After upgrade to React 16.9.0, React prints console warning because react-css-collapse still uses `componentWillReceiveProps` life-cycle method. This method will be removed in React 17.0.0.
Would you please rewrite the code to make it work after React 17.0.0 release?
Thank you!

**Comment by thalseth** [comment]
Fixed by @cdeutsch in https://github.com/SparebankenVest/react-css-collapse/releases/tag/v3.6.1 💯
