### ISSUE TITLE
overflow:'hidden' on the first render when isOpen = true

### ISSUE THREAD

**Issue by LuchistiyPirozhok** [SparebankenVest/react-css-collapse#41]
Hi! It seems like [this](https://github.com/SparebankenVest/react-css-collapse/issues/9) problem appears again. Here is a small example https://codesandbox.io/s/naughty-lederberg-ngz5t

**Comment by thalseth** [comment]
Hi @LuchistiyPirozhok , thanks for reporting this. Im on it.

**Comment by thalseth** [comment]
This should be fixed now in 4.0.6 @LuchistiyPirozhok.

**Comment by LuchistiyPirozhok** [comment]
Yeap seems fine. Thank you!
