### ISSUE TITLE
`overflow: hidden` should be removed after initial render when `isOpen={true}`

### ISSUE THREAD

**Issue by mshwery** [SparebankenVest/react-css-collapse#9]
First off thanks for this component – came in handy in a pinch.

I have children components that have dropdowns that might spill over beyond the `<Collapse />` parent component's height. The problem I'm encountering only happens when the initial render has `isOpen={true}`.

The inline style `overflow: hidden` is applied and remains on the component until you switch the state from `isOpen={false}`. In fact, once you toggle it yet again to `isOpen={true}` after being in the `isOpen={false}` state it does remove the `overflow: hidden` style with `overflow: visible`, which is what my child components require after the animation is complete.

**Comment by thalseth** [comment]
Hi Matt! I am glad the component works for you. 
What version of the package are you using?
It would be very nice to [provide an example](https://github.com/SparebankenVest/react-css-collapse/blob/master/CONTRIBUTING.md#think-you-found-a-bug) for me to fully understand the issue.

**Comment by mshwery** [comment]
Here's an example of a dropdown component that gets cut off by the initial inline styles of `Collapse`: https://codesandbox.io/s/Dk1woW3xB

**Comment by thalseth** [comment]
Fixed by @mshwery here: https://github.com/SparebankenVest/react-css-collapse/pull/10
